# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hand schema control to Flyway, Hibernate does nothing
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# H2 Console - never in prod
spring.h2.console.enabled=false

# SSL for Supabase
spring.datasource.hikari.data-source-properties.sslmode=require