CREATE TABLE doctors (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         full_name VARCHAR(255) NOT NULL,
                         email VARCHAR(255) NOT NULL UNIQUE,
                         phone_number VARCHAR(255) NOT NULL,
                         specialty VARCHAR(255) NOT NULL,
                         license_number VARCHAR(255) NOT NULL UNIQUE,
                         created_at TIMESTAMP NOT NULL,
                         created_by_id BIGINT,
                         updated_at TIMESTAMP NOT NULL,
                         updated_by_id BIGINT,
                         ip_address VARCHAR(45)
);

CREATE TABLE patients (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          full_name VARCHAR(255) NOT NULL,
                          date_of_birth DATE NOT NULL,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          phone_number VARCHAR(255) NOT NULL,
                          preferred_doctor_id BIGINT,
                          created_at TIMESTAMP NOT NULL,
                          created_by_id BIGINT,
                          updated_at TIMESTAMP NOT NULL,
                          updated_by_id BIGINT,
                          ip_address VARCHAR(45),
                          CONSTRAINT fk_patient_preferred_doctor
                              FOREIGN KEY (preferred_doctor_id) REFERENCES doctors(id)
);

CREATE TABLE doctor_availability (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     doctor_id BIGINT NOT NULL,
                                     day_of_week VARCHAR(10) NOT NULL,
                                     start_time TIME NOT NULL,
                                     end_time TIME NOT NULL,
                                     created_at TIMESTAMP NOT NULL,
                                     created_by_id BIGINT,
                                     updated_at TIMESTAMP NOT NULL,
                                     updated_by_id BIGINT,
                                     ip_address VARCHAR(45),
                                     CONSTRAINT fk_availability_doctor
                                         FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

CREATE TABLE appointments (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              patient_id BIGINT NOT NULL,
                              doctor_id BIGINT NOT NULL,
                              appointment_datetime TIMESTAMP NOT NULL,
                              reason VARCHAR(255) NOT NULL,
                              status VARCHAR(50) NOT NULL,
                              created_at TIMESTAMP NOT NULL,
                              created_by_id BIGINT,
                              updated_at TIMESTAMP NOT NULL,
                              updated_by_id BIGINT,
                              ip_address VARCHAR(45),
                              CONSTRAINT fk_appointment_patient
                                  FOREIGN KEY (patient_id) REFERENCES patients(id),
                              CONSTRAINT fk_appointment_doctor
                                  FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);